In [5]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [6]:
url ='https://en.wikipedia.org/wiki/List_of_epidemics_and_pandemics'
headers = {
    'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0'
}

In [7]:
soup = requests.get(url, headers= headers)

In [8]:
webpage = BeautifulSoup(soup.text, 'html')

In [9]:
target_tables = webpage.find_all('table')[2:]

In [10]:
table1 = target_tables[0]

In [11]:
table_headers = [header.text for header in table1.find_all('th')]

In [12]:
df = pd.DataFrame(columns = table_headers)

In [13]:
column_data = table1.find_all('tr')
column_data

[<tr id="mwAZs">
 <th id="mwAZw" scope="col">Event</th>
 <th data-sort-type="isoDate" id="mwAZ0" scope="col">Years</th>
 <th id="mwAZ4" scope="col">Location</th>
 <th id="mwAZ8" scope="col">Disease</th>
 <th data-sort-type="number" id="mwAaA" scope="col">Death toll (estimate)</th>
 <th id="mwAaE">Ref.</th></tr>,
 <tr id="mwAaI">
 <td id="mwAaM"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["1350 BC plague of Megiddo"]}}' href="https://en.wikipedia.org/wiki/1350_BC_plague_of_Megiddo?action=edit&amp;redlink=1" id="mwAaQ" rel="mw:WikiLink" title="1350 BC plague of Megiddo (page does not exist)" typeof="mw:LocalizedAttrs">1350 BC plague of Megiddo</a></td>
 <td data-sort-value="-1350" id="mwAaU">1350 BC (circa)</td>
 <td id="mwAaY"><a href="https://en.wikipedia.org/wiki/Tel_Megiddo" id="mwAac" rel="mw:WikiLink" title="Tel Megiddo">Megiddo</a>, land of <a href="https://en.wikipedia.org/wiki/Canaan" id="mwAag" rel="mw:WikiLink" title="Canaan">Canaan</a></td>
 <td id="mwAak">Unknown. In the <a href="https://en.wikipedia.org/wiki/Amarna_letters" id="mwAao" rel="mw:WikiLink" title="Amarna letters">Amarna letters</a> EA 244, <a href="https://en.wikipedia.org/wiki/Biridiya" id="mwAas" rel="mw:WikiLink" title="Biridiya">Biridiya</a>, the mayor of Megiddo complains to <a href="https://en.wikipedia.org/wiki/Amenhotep_III" id="mwAaw" rel="mw:WikiLink" title="Amenhotep III">Amenhotep III</a> of his area being "consumed by death, plague and dust"</td>
 <td about="#mwt102" class="table-Unknown" data-mw='{"parts":["| data-sort-value=\"0\" ",{"template":{"target":{"wt":"dunno","href":"./Template:Dunno"},"params":{},"i":0}}]}' data-sort-value="0" id="mwAa0" style="background: var(--background-color-interactive, #EEE); color: var(--color-base, black); vertical-align: middle; text-align: center; " typeof="mw:Transclusion">?</td>
 <td id="mwAa4"><sup about="#mwt104" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Amarna"},"body":{"id":"mw-reference-text-cite_note-Amarna-28"}}' id="cite_ref-Amarna_28-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Amarna-28" id="mwAa8"><span class="mw-reflink-text" id="mwAbA"><span class="cite-bracket" id="mwAbE">[</span>28<span class="cite-bracket" id="mwAbI">]</span></span></a></sup></td></tr>,
 <tr id="mwAbM">
 <td id="mwAbQ"><a href="https://en.wikipedia.org/wiki/Hittite_plague" id="mwAbU" rel="mw:WikiLink" title="Hittite plague">Hittite Plague</a>/"Hand of Nergal"</td>
 <td id="mwAbY">1330 BC (circa)</td>
 <td id="mwAbc"><a href="https://en.wikipedia.org/wiki/Near_East" id="mwAbg" rel="mw:WikiLink" title="Near East">Near East</a>, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Hittite_Empire" id="mwAbk" rel="mw:WikiLink" title="Hittite Empire">Hittite Empire</a>, <a href="https://en.wikipedia.org/wiki/Alashiya" id="mwAbo" rel="mw:WikiLink" title="Alashiya">Alashiya</a>, possibly <a href="https://en.wikipedia.org/wiki/New_Kingdom_of_Egypt" id="mwAbs" rel="mw:WikiLink" title="New Kingdom of Egypt">Egypt</a></td>
 <td id="mwAbw">Unknown, possibly <a href="https://en.wikipedia.org/wiki/Tularemia" id="mwAb0" rel="mw:WikiLink" title="Tularemia">Tularemia</a>. Mentioned in <a href="https://en.wikipedia.org/wiki/Amarna_letter_EA_35" id="mwAb4" rel="mw:WikiLink" title="Amarna letter EA 35">Amarna letter EA 35</a> as the "Hand of Nergal", cause of death of <a href="https://en.wikipedia.org/wiki/Šuppiluliuma_I" id="mwAb8" rel="mw:WikiLink" title="Šuppiluliuma I">Šuppiluliuma I</a>.</td>
 <td about="#mwt105" class="table-Unknown" data-mw='{"parts":["| data-sort-value=\"0\" ",{"template":{"target":{"wt":"dunno","href":"./Template:Dunno"},"params":{},"i":0}}]}' data-sort-value="0" id="mwAcA" style="background: var(--background-color-interactive, #EEE); color: var(--color-base, black); vertical-align: middle; text-align: center; " typeof="mw:Transclusion">?</td>
 <td id="mwAcE"></td></tr>,
 <tr id="mwAcI">
 <td id="mwAcM"><a href="https://en.wikipedia.org/wiki/Plague_of_Athens" id="mwAcQ" rel="mw:WikiLink" title="Plague of Athens">Plague of Athens</a></td>
 <td data-sort-value="-430" id="mwAcU">430–426 BC</td>
 <td id="mwAcY">Greece, <a href="https://en.wikipedia.org/wiki/Libya" id="mwAcc" rel="mw:WikiLink" title="Libya">Libya</a>, Egypt, <a href="https://en.wikipedia.org/wiki/Ethiopia" id="mwAcg" rel="mw:WikiLink" title="Ethiopia">Ethiopia</a></td>
 <td id="mwAck">Unknown, possibly <a href="https://en.wikipedia.org/wiki/Typhus" id="mwAco" rel="mw:WikiLink" title="Typhus">typhus</a>, <a href="https://en.wikipedia.org/wiki/Typhoid_fever" id="mwAcs" rel="mw:WikiLink" title="Typhoid fever">typhoid fever</a> or <a href="https://en.wikipedia.org/wiki/Viral_hemorrhagic_fever" id="mwAcw" rel="mw:WikiLink" title="Viral hemorrhagic fever">viral hemorrhagic fever</a></td>
 <td data-sort-value="87500" id="mwAc0">75,000–100,000</td>
 <td id="mwAc4"><sup about="#mwt108" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-29"}}' id="cite_ref-29" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-29" id="mwAc8"><span class="mw-reflink-text" id="mwAdA"><span class="cite-bracket" id="mwAdE">[</span>29<span class="cite-bracket" id="mwAdI">]</span></span></a></sup><sup about="#mwt111" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-30"}}' id="cite_ref-30" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-30" id="mwAdM"><span class="mw-reflink-text" id="mwAdQ"><span class="cite-bracket" id="mwAdU">[</span>30<span class="cite-bracket" id="mwAdY">]</span></span></a></sup><sup about="#mwt114" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-31"}}' id="cite_ref-31" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-31" id="mwAdc"><span class="mw-reflink-text" id="mwAdg"><span class="cite-bracket" id="mwAdk">[</span>31<span class="cite-bracket" id="mwAdo">]</span></span></a></sup><sup about="#mwt117" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-32"}}' id="cite_ref-32" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-32" id="mwAds"><span class="mw-reflink-text" id="mwAdw"><span class="cite-bracket" id="mwAd0">[</span>32<span class="cite-bracket" id="mwAd4">]</span></span></a></sup></td></tr>,
 <tr id="mwAd8">
 <td id="mwAeA"><a href="https://en.wikipedia.org/wiki/412_BC_epidemic" id="mwAeE" rel="mw:WikiLink" title="412 BC epidemic">412 BC epidemic</a></td>
 <td data-sort-value="-412" id="mwAeI">412 BC</td>
 <td id="mwAeM">Greece (<a href="https://en.wikipedia.org/wiki/Northern_Greece" id="mwAeQ" rel="mw:WikiLink" title="Northern Greece">Northern Greece</a>, <a href="https://en.wikipedia.org/wiki/Roman_Republic" id="mwAeU" rel="mw:WikiLink" title="Roman Republic">Roman Republic</a>)</td>
 <td id="mwAeY">Unknown, possibly <a href="https://en.wikipedia.org/wiki/Influenza" id="mwAec" rel="mw:WikiLink" title="Influenza">influenza</a></td>
 <td data-sort-value="473000" id="mwAeg">473,000 (10% of the Roman Population)</td>
 <td id="mwAek"><sup about="#mwt120" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-33"}}' id="cite_ref-33" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-33" id="mwAeo"><span class="mw-reflink-text" id="mwAes"><span class="cite-bracket" id="mwAew">[</span>33<span class="cite-bracket" id="mwAe0">]</span></span></a></sup></td></tr>,
 <tr id="mwAe4">
 <td id="mwAe8"><a href="https://en.wikipedia.org/wiki/Antonine_Plague" id="mwAfA" rel="mw:WikiLink" title="Antonine Plague">Antonine Plague</a></td>
 <td data-sort-value="0165" id="mwAfE">165–180 (possibly up to 190)</td>
 <td id="mwAfI"><a href="https://en.wikipedia.org/wiki/Roman_Empire" id="mwAfM" rel="mw:WikiLink" title="Roman Empire">Roman Empire</a></td>
 <td id="mwAfQ">Unknown, possibly <a href="https://en.wikipedia.org/wiki/Smallpox" id="mwAfU" rel="mw:WikiLink" title="Smallpox">smallpox</a></td>
 <td data-sort-value="07500000" id="mwAfY">5–10 million</td>
 <td id="mwAfc"><sup about="#mwt123" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-34"}}' id="cite_ref-34" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-34" id="mwAfg"><span class="mw-reflink-text" id="mwAfk"><span class="cite-bracket" id="mwAfo">[</span>34<span class="cite-bracket" id="mwAfs">]</span></span></a></sup><sup about="#mwt124" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-35"}}' id="cite_ref-35" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-35" id="mwAfw"><span class="mw-reflink-text" id="mwAf0"><span class="cite-bracket" id="mwAf4">[</span>35<span class="cite-bracket" id="mwAf8">]</span></span></a></sup></td></tr>,
 <tr id="mwAgA">
 <td id="mwAgE"><a class="new" data-mw-i18n="{&quot;title&quot;:{&quot;lang&quot;:&quot;x-page&quot;,&quot;key&quot;:&quot;red-link-title&quot;,&quot;params&quot;:[&quot;Jian'an Plague&quot;]}}" href="https://en.wikipedia.org/wiki/Jian'an_Plague?action=edit&amp;redlink=1" id="mwAgI" rel="mw:WikiLink" title="Jian'an Plague (page does not exist)" typeof="mw:LocalizedAttrs">Jian'an Plague</a></td>
 <td id="mwAgM">217</td>
 <td id="mwAgQ"><a href="https://en.wikipedia.org/wiki/Han_dynasty#Eastern_Han" id="mwAgU" rel="mw:WikiLink" title="Han dynasty">Han dynasty</a></td>
 <td id="mwAgY">Unknown, possibly <a href="https://en.wikipedia.org/wiki/Typhoid_fever" id="mwAgc" rel="mw:WikiLink" title="Typhoid fever">typhoid fever</a> or <a href="https://en.wikipedia.org/wiki/Viral_hemorrhagic_fever" id="mwAgg" rel="mw:WikiLink" title="Viral hemorrhagic fever">viral hemorrhagic fever</a></td>
 <td data-sort-value="2000000" id="mwAgk">2 million</td>
 <td id="mwAgo"><sup about="#mwt125" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"review_the_halberd"}}' id="cite_ref-review_the_halberd_12-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-review_the_halberd-12" id="mwAgs"><span class="mw-reflink-text" id="mwAgw"><span class="cite-bracket" id="mwAg0">[</span>12<span class="cite-bracket" id="mwAg4">]</span></span></a></sup><sup about="#mwt126" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"the_halberd_at"}}' id="cite_ref-the_halberd_at_13-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-the_halberd_at-13" id="mwAg8"><span class="mw-reflink-text" id="mwAhA"><span class="cite-bracket" id="mwAhE">[</span>13<span class="cite-bracket" id="mwAhI">]</span></span></a></sup></td></tr>,
 <tr id="mwAhM">
 <td id="mwAhQ"><a href="https://en.wikipedia.org/wiki/Plague_of_Cyprian" id="mwAhU" rel="mw:WikiLink" title="Plague of Cyprian">Plague of Cyprian</a></td>
 <td data-sort-value="0249" id="mwAhY">249–262</td>
 <td id="mwAhc">Europe</td>
 <td id="mwAhg">Unknown, possibly <a href="https://en.wikipedia.org/wiki/Smallpox" id="mwAhk" rel="mw:WikiLink" title="Smallpox">smallpox</a> or <a href="https://en.wikipedia.org/wiki/Viral_hemorrhagic_fever" id="mwAho" rel="mw:WikiLink" title="Viral hemorrhagic fever">viral hemorrhagic fever</a></td>
 <td data-sort-value="310000" id="mwAhs">310,000</td>
 <td id="mwAhw"><sup about="#mwt127" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-36"}}' id="cite_ref-36" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-36" id="mwAh0"><span class="mw-reflink-text" id="mwAh4"><span class="cite-bracket" id="mwAh8">[</span>36<span class="cite-bracket" id="mwAiA">]</span></span></a></sup><sup about="#mwt130" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-37"}}' id="cite_ref-37" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-37" id="mwAiE"><span class="mw-reflink-text" id="mwAiI"><span class="cite-bracket" id="mwAiM">[</span>37<span class="cite-bracket" id="mwAiQ">]</span></span></a></sup><sup about="#mwt133" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-38"}}' id="cite_ref-38" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-38" id="mwAiU"><span class="mw-reflink-text" id="mwAiY"><span class="cite-bracket" id="mwAic">[</span>38<span class="cite-bracket" id="mwAig">]</span></span></a></sup></td></tr>,
 <tr id="mwAik">
 <td id="mwAio"><a href="https://en.wikipedia.org/wiki/Plague_of_Justinian" id="mwAis" rel="mw:WikiLink" title="Plague of Justinian">Plague of Justinian</a> (beginning of <a href="https://en.wikipedia.org/wiki/First_plague_pandemic" id="mwAiw" rel="mw:WikiLink" title="First plague pandemic">first plague pandemic</a>)</td>
 <td data-sort-value="0541" id="mwAi0">541–549</td>
 <td id="mwAi4">Europe and <a href="https://en.wikipedia.org/wiki/West_Asia" id="mwAi8" rel="mw:WikiLink" title="West Asia">West Asia</a></td>
 <td id="mwAjA"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwAjE" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="057500000" id="mwAjI">15–100 million</td>
 <td id="mwAjM"><sup about="#mwt136" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":":4"},"body":{"id":"mw-reference-text-cite_note-:4-4"}}' id="cite_ref-:4_4-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-:4-4" id="mwAjQ"><span class="mw-reflink-text" id="mwAjU"><span class="cite-bracket" id="mwAjY">[</span>4<span class="cite-bracket" id="mwAjc">]</span></span></a></sup><sup about="#mwt139" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-39"}}' id="cite_ref-39" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-39" id="mwAjg"><span class="mw-reflink-text" id="mwAjk"><span class="cite-bracket" id="mwAjo">[</span>39<span class="cite-bracket" id="mwAjs">]</span></span></a></sup><sup about="#mwt142" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-40"}}' id="cite_ref-40" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-40" id="mwAjw"><span class="mw-reflink-text" id="mwAj0"><span class="cite-bracket" id="mwAj4">[</span>40<span class="cite-bracket" id="mwAj8">]</span></span></a></sup></td></tr>,
 <tr id="mwAkA">
 <td id="mwAkE"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/580_Dysentery_Epidemic_in_Gaul" id="mwAkI" rel="mw:WikiLink" title="580 Dysentery Epidemic in Gaul">580 Dysentery Epidemic in Gaul</a></td>
 <td data-sort-value="0580" id="mwAkM">580</td>
 <td id="mwAkQ"><a href="https://en.wikipedia.org/wiki/Gaul" id="mwAkU" rel="mw:WikiLink" title="Gaul">Gaul</a></td>
 <td id="mwAkY">Dysentery or possibly smallpox</td>
 <td data-sort-value="450000" id="mwAkc">450,000 (10% of the <a href="https://en.wikipedia.org/wiki/Gaul" id="mwAkg" rel="mw:WikiLink" title="Gaul">Gaul</a> population)</td>
 <td id="mwAkk"><sup about="#mwt143" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-41"}}' id="cite_ref-41" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-41" id="mwAko"><span class="mw-reflink-text" id="mwAks"><span class="cite-bracket" id="mwAkw">[</span>41<span class="cite-bracket" id="mwAk0">]</span></span></a></sup></td></tr>,
 <tr id="mwAk4">
 <td id="mwAk8"><a href="https://en.wikipedia.org/wiki/Roman_Plague_of_590" id="mwAlA" rel="mw:WikiLink" title="Roman Plague of 590">Roman Plague of 590</a> (part of <a href="https://en.wikipedia.org/wiki/First_plague_pandemic" id="mwAlE" rel="mw:WikiLink" title="First plague pandemic">first plague pandemic</a>)</td>
 <td data-sort-value="0590" id="mwAlI">590</td>
 <td id="mwAlM"><a href="https://en.wikipedia.org/wiki/Rome" id="mwAlQ" rel="mw:WikiLink" title="Rome">Rome</a>, <a href="https://en.wikipedia.org/wiki/Byzantine_Empire" id="mwAlU" rel="mw:WikiLink" title="Byzantine Empire">Byzantine Empire</a></td>
 <td id="mwAlY"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwAlc" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td about="#mwt144" class="table-Unknown" data-mw='{"parts":["| data-sort-value=\"0\" ",{"template":{"target":{"wt":"dunno","href":"./Template:Dunno"},"params":{},"i":0}}]}' data-sort-value="0" id="mwAlg" style="background: var(--background-color-interactive, #EEE); color: var(--color-base, black); vertical-align: middle; text-align: center; " typeof="mw:Transclusion">?</td>
 <td id="mwAlk"><sup about="#mwt147" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-42"}}' id="cite_ref-42" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-42" id="mwAlo"><span class="mw-reflink-text" id="mwAls"><span class="cite-bracket" id="mwAlw">[</span>42<span class="cite-bracket" id="mwAl0">]</span></span></a></sup></td></tr>,
 <tr id="mwAl4">
 <td id="mwAl8"><a href="https://en.wikipedia.org/wiki/Plague_of_Sheroe" id="mwAmA" rel="mw:WikiLink" title="Plague of Sheroe">Plague of Sheroe</a> (part of <a href="https://en.wikipedia.org/wiki/First_plague_pandemic" id="mwAmE" rel="mw:WikiLink" title="First plague pandemic">first plague pandemic</a>)</td>
 <td data-sort-value="0627" id="mwAmI">627–628</td>
 <td id="mwAmM"><a href="https://en.wikipedia.org/wiki/Bilad_al-Sham" id="mwAmQ" rel="mw:WikiLink" title="Bilad al-Sham">Bilad al-Sham</a></td>
 <td id="mwAmU"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwAmY" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="25001" id="mwAmc">25,000+</td>
 <td id="mwAmg"></td></tr>,
 <tr id="mwAmk">
 <td id="mwAmo"><a href="https://en.wikipedia.org/wiki/Plague_of_Amwas" id="mwAms" rel="mw:WikiLink" title="Plague of Amwas">Plague of Amwas</a> (part of <a href="https://en.wikipedia.org/wiki/First_plague_pandemic" id="mwAmw" rel="mw:WikiLink" title="First plague pandemic">first plague pandemic</a>)</td>
 <td data-sort-value="0638" id="mwAm0">638–639</td>
 <td id="mwAm4"><a href="https://en.wikipedia.org/wiki/Byzantine_Empire" id="mwAm8" rel="mw:WikiLink" title="Byzantine Empire">Byzantine Empire</a>, <a href="https://en.wikipedia.org/wiki/West_Asia" id="mwAnA" rel="mw:WikiLink" title="West Asia">West Asia</a>, Africa</td>
 <td id="mwAnE"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwAnI" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="25001" id="mwAnM">25,000+</td>
 <td id="mwAnQ"><sup about="#mwt150" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Turner1990"},"body":{"id":"mw-reference-text-cite_note-Turner1990-43"}}' id="cite_ref-Turner1990_43-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Turner1990-43" id="mwAnU"><span class="mw-reflink-text" id="mwAnY"><span class="cite-bracket" id="mwAnc">[</span>43<span class="cite-bracket" id="mwAng">]</span></span></a></sup></td></tr>,
 <tr id="mwAnk">
 <td id="mwAno"><a href="https://en.wikipedia.org/wiki/Plague_of_664" id="mwAns" rel="mw:WikiLink" title="Plague of 664">Plague of 664</a> (part of <a href="https://en.wikipedia.org/wiki/First_plague_pandemic" id="mwAnw" rel="mw:WikiLink" title="First plague pandemic">first plague pandemic</a>)</td>
 <td data-sort-value="0664" id="mwAn0">664–689</td>
 <td id="mwAn4"><a href="https://en.wikipedia.org/wiki/British_Isles" id="mwAn8" rel="mw:WikiLink" title="British Isles">British Isles</a></td>
 <td id="mwAoA"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwAoE" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>

In [14]:
for row in column_data[1:-1]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
     
    length = len(df)   
    df.loc[length] = individual_row_data

In [15]:
df

,Event,Years,Location,Disease,Death toll (estimate),Ref.
0,1350 BC plague of Megiddo,1350 BC (circa),"Megiddo, land of Canaan","Unknown. In the Amarna letters EA 244, Biridiy...",?,[28]
1,"Hittite Plague/""Hand of Nergal""",1330 BC (circa),"Near East, Hittite Empire, Alashiya, possibly ...","Unknown, possibly Tularemia. Mentioned in Amar...",?,
2,Plague of Athens,430–426 BC,"Greece, Libya, Egypt, Ethiopia","Unknown, possibly typhus, typhoid fever or vir...","75,000–100,000",[29][30][31][32]
3,412 BC epidemic,412 BC,"Greece (Northern Greece, Roman Republic)","Unknown, possibly influenza","473,000 (10% of the Roman Population)",[33]
4,Antonine Plague,165–180 (possibly up to 190),Roman Empire,"Unknown, possibly smallpox",5–10 million,[34][35]
5,Jian'an Plague,217,Han dynasty,"Unknown, possibly typhoid fever or viral hemor...",2 million,[12][13]
6,Plague of Cyprian,249–262,Europe,"Unknown, possibly smallpox or viral hemorrhagi...","310,000",[36][37][38]
7,Plague of Justinian (beginning of first plague...,541–549,Europe and West Asia,Bubonic plague,15–100 million,[4][39][40]
8,580 Dysentery Epidemic in Gaul,580,Gaul,Dysentery or possibly smallpox,"450,000 (10% of the Gaul population)",[41]
9,Roman Plague of 590 (part of first plague pand...,590,"Rome, Byzantine Empire",Bubonic plague,?,[42]
10,Plague of Sheroe (part of first plague pandemic),627–628,Bilad al-Sham,Bubonic plague,"25,000+",
11,Plague of Amwas (part of first plague pandemic),638–639,"Byzantine Empire, West Asia, Africa",Bubonic plague,"25,000+",[43]
12,Plague of 664 (part of first plague pandemic),664–689,British Isles,Bubonic plague,?,[44]
13,Plague of 698–701 (part of first plague pandemic),698–701,"Byzantine Empire, West Asia, Syria, Mesopotamia",Bubonic plague,?,[45]
14,735–737 Japanese smallpox epidemic,735–737,Japan,Smallpox,2 million (approx. 1⁄3 of Japanese population),[14][46]
15,Plague of 746–747 (part of first plague pandemic),746–747,"Byzantine Empire, West Asia, Africa",Bubonic plague,?,[43]
16,Black Death (start of the second plague pandemic),1346–1353,Eurasia and North Africa,Bubonic plague,25–50 million (30–60% of European population a...,[47]
17,Sweating sickness (multiple outbreaks),1485–1551,Britain (England) and later continental Europe,"Unknown, possibly an unknown species of hantav...","10,000+",[48]
18,1489 Spain typhus epidemic,1489,Spain,Typhus,"17,000",[49]

In [16]:
# Now for table 2

table2 = target_tables[1]

In [17]:
column_dataB = table2.find_all('tr')
column_dataB

[<tr id="mwAuw">
 <th id="mwAu0" scope="col">Event</th>
 <th data-sort-type="isoDate" id="mwAu4" scope="col">Years</th>
 <th id="mwAu8" scope="col">Location</th>
 <th id="mwAvA" scope="col">Disease</th>
 <th data-sort-type="number" id="mwAvE" scope="col">Death toll (estimate)</th>
 <th id="mwAvI">Ref.</th></tr>,
 <tr id="mwAvM">
 <td id="mwAvQ"><a href="https://en.wikipedia.org/wiki/1510_influenza_pandemic" id="mwAvU" rel="mw:WikiLink" title="1510 influenza pandemic">1510 influenza pandemic</a></td>
 <td id="mwAvY">1510</td>
 <td id="mwAvc">Asia, <a href="https://en.wikipedia.org/wiki/North_Africa" id="mwAvg" rel="mw:WikiLink" title="North Africa">North Africa</a>, Europe</td>
 <td id="mwAvk"><a href="https://en.wikipedia.org/wiki/Influenza" id="mwAvo" rel="mw:WikiLink" title="Influenza">Influenza</a></td>
 <td data-sort-value="0" id="mwAvs">Unknown, around 1% of those infected</td>
 <td id="mwAvw"><sup about="#mwt180" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-50"}}' id="cite_ref-50" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-50" id="mwAv0"><span class="mw-reflink-text" id="mwAv4"><span class="cite-bracket" id="mwAv8">[</span>50<span class="cite-bracket" id="mwAwA">]</span></span></a></sup></td></tr>,
 <tr id="mwAwE">
 <td id="mwAwI"><a href="https://en.wikipedia.org/wiki/History_of_smallpox_in_Mexico" id="mwAwM" rel="mw:WikiLink" title="History of smallpox in Mexico">1520 Mexico smallpox epidemic</a></td>
 <td id="mwAwQ">1519–1520</td>
 <td id="mwAwU"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Viceroyalty_of_New_Spain" id="mwAwY" rel="mw:WikiLink" title="Viceroyalty of New Spain">Mexico</a></td>
 <td id="mwAwc"><a href="https://en.wikipedia.org/wiki/Smallpox" id="mwAwg" rel="mw:WikiLink" title="Smallpox">Smallpox</a></td>
 <td data-sort-value="6500000" id="mwAwk">5–8 million (40% of population)</td>
 <td id="mwAwo"><sup about="#mwt183" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Acuna-SotoStahle2002"},"body":{"id":"mw-reference-text-cite_note-Acuna-SotoStahle2002-9"}}' id="cite_ref-Acuna-SotoStahle2002_9-3" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Acuna-SotoStahle2002-9" id="mwAws"><span class="mw-reflink-text" id="mwAww"><span class="cite-bracket" id="mwAw0">[</span>9<span class="cite-bracket" id="mwAw4">]</span></span></a></sup></td></tr>,
 <tr id="mwAw8">
 <td id="mwAxA"><a href="https://en.wikipedia.org/wiki/Cocoliztli_epidemics" id="mwAxE" rel="mw:WikiLink" title="Cocoliztli epidemics">Cocoliztli epidemic of 1545–1548</a></td>
 <td id="mwAxI">1545–1548</td>
 <td id="mwAxM"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Viceroyalty_of_New_Spain" id="mwAxQ" rel="mw:WikiLink" title="Viceroyalty of New Spain">Mexico</a></td>
 <td id="mwAxU">Possibly <i id="mwAxY"><a href="https://en.wikipedia.org/wiki/Salmonella_enterica" id="mwAxc" rel="mw:WikiLink" title="Salmonella enterica">Salmonella enterica</a></i></td>
 <td data-sort-value="010000000" id="mwAxg">5–15 million (80% of population)</td>
 <td id="mwAxk"><sup about="#mwt186" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"American plague"},"body":{"id":"mw-reference-text-cite_note-American_plague-51"}}' id="cite_ref-American_plague_51-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-American_plague-51" id="mwAxo"><span class="mw-reflink-text" id="mwAxs"><span class="cite-bracket" id="mwAxw">[</span>51<span class="cite-bracket" id="mwAx0">]</span></span></a></sup><sup about="#mwt189" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Acuna-SotoRomero2000"},"body":{"id":"mw-reference-text-cite_note-Acuna-SotoRomero2000-52"}}' id="cite_ref-Acuna-SotoRomero2000_52-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Acuna-SotoRomero2000-52" id="mwAx4"><span class="mw-reflink-text" id="mwAx8"><span class="cite-bracket" id="mwAyA">[</span>52<span class="cite-bracket" id="mwAyE">]</span></span></a></sup><sup about="#mwt190" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Acuna-SotoStahle2002"}}' id="cite_ref-Acuna-SotoStahle2002_9-4" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Acuna-SotoStahle2002-9" id="mwAyI"><span class="mw-reflink-text" id="mwAyM"><span class="cite-bracket" id="mwAyQ">[</span>9<span class="cite-bracket" id="mwAyU">]</span></span></a></sup><sup about="#mwt193" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sal"},"body":{"id":"mw-reference-text-cite_note-sal-53"}}' id="cite_ref-sal_53-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-sal-53" id="mwAyY"><span class="mw-reflink-text" id="mwAyc"><span class="cite-bracket" id="mwAyg">[</span>53<span class="cite-bracket" id="mwAyk">]</span></span></a></sup></td></tr>,
 <tr id="mwAyo">
 <td id="mwAys"><a href="https://en.wikipedia.org/wiki/1557_influenza_pandemic" id="mwAyw" rel="mw:WikiLink" title="1557 influenza pandemic">1557 influenza pandemic</a></td>
 <td id="mwAy0">1557–1559</td>
 <td id="mwAy4">Asia, Africa, Europe, and <a href="https://en.wikipedia.org/wiki/Americas" id="mwAy8" rel="mw:WikiLink" title="Americas">Americas</a></td>
 <td id="mwAzA"><a href="https://en.wikipedia.org/wiki/Influenza" id="mwAzE" rel="mw:WikiLink" title="Influenza">Influenza</a></td>
 <td id="mwAzI">Unknown (10% of the infected)</td>
 <td id="mwAzM"></td></tr>,
 <tr id="mwAzQ">
 <td id="mwAzU"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["1561 Chile smallpox epidemic"]}}' href="https://en.wikipedia.org/wiki/1561_Chile_smallpox_epidemic?action=edit&amp;redlink=1" id="mwAzY" rel="mw:WikiLink" title="1561 Chile smallpox epidemic (page does not exist)" typeof="mw:LocalizedAttrs">1561 Chile smallpox epidemic</a></td>
 <td id="mwAzc">1561–1562</td>
 <td id="mwAzg"><a href="https://en.wikipedia.org/wiki/Captaincy_General_of_Chile" id="mwAzk" rel="mw:WikiLink" title="Captaincy General of Chile">Chile</a></td>
 <td id="mwAzo"><a href="https://en.wikipedia.org/wiki/Smallpox" id="mwAzs" rel="mw:WikiLink" title="Smallpox">Smallpox</a></td>
 <td data-sort-value="135,000" id="mwAzw">120,000–150,000 (20–25% of native population)</td>
 <td id="mwAz0"><sup about="#mwt195" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-54"}}' id="cite_ref-54" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-54" id="mwAz4"><span class="mw-reflink-text" id="mwAz8"><span class="cite-bracket" id="mwA0A">[</span>54<span class="cite-bracket" id="mwA0E">]</span></span></a></sup></td></tr>,
 <tr id="mwA0I">
 <td id="mwA0M"><a href="https://en.wikipedia.org/wiki/1563_London_plague" id="mwA0Q" rel="mw:WikiLink" title="1563 London plague">1563 London plague</a> (part of the <a href="https://en.wikipedia.org/wiki/Second_plague_pandemic" id="mwA0U" rel="mw:WikiLink" title="Second plague pandemic">second plague pandemic</a>)</td>
 <td id="mwA0Y">1563–1564</td>
 <td id="mwA0c"><a href="https://en.wikipedia.org/wiki/London" id="mwA0g" rel="mw:WikiLink" title="London">London</a>, England</td>
 <td id="mwA0k"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwA0o" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="20101" id="mwA0s">20,100+</td>
 <td id="mwA0w"><sup about="#mwt198" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-55"}}' id="cite_ref-55" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-55" id="mwA00"><span class="mw-reflink-text" id="mwA04"><span class="cite-bracket" id="mwA08">[</span>55<span class="cite-bracket" id="mwA1A">]</span></span></a></sup></td></tr>,
 <tr id="mwA1E">
 <td id="mwA1I"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cocoliztli_epidemic_of_1576" id="mwA1M" rel="mw:WikiLink" title="Cocoliztli epidemic of 1576">Cocoliztli epidemic of 1576</a></td>
 <td id="mwA1Q">1576–1580</td>
 <td id="mwA1U"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Viceroyalty_of_New_Spain" id="mwA1Y" rel="mw:WikiLink" title="Viceroyalty of New Spain">Mexico</a></td>
 <td id="mwA1c"><a href="https://en.wikipedia.org/wiki/Salmonella_enterica" id="mwA1g" rel="mw:WikiLink" title="Salmonella enterica">Possibly <i id="mwA1k">Salmonella enterica</i></a></td>
 <td data-sort-value="2250000" id="mwA1o">2–2.5 million (50% of population)</td>
 <td id="mwA1s"><sup about="#mwt199" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"American plague"}}' id="cite_ref-American_plague_51-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-American_plague-51" id="mwA1w"><span class="mw-reflink-text" id="mwA10"><span class="cite-bracket" id="mwA14">[</span>51<span class="cite-bracket" id="mwA18">]</span></span></a></sup><sup about="#mwt200" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Acuna-SotoRomero2000"}}' id="cite_ref-Acuna-SotoRomero2000_52-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Acuna-SotoRomero2000-52" id="mwA2A"><span class="mw-reflink-text" id="mwA2E"><span class="cite-bracket" id="mwA2I">[</span>52<span class="cite-bracket" id="mwA2M">]</span></span></a></sup><sup about="#mwt201" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Acuna-SotoStahle2002"}}' id="cite_ref-Acuna-SotoStahle2002_9-5" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Acuna-SotoStahle2002-9" id="mwA2Q"><span class="mw-reflink-text" id="mwA2U"><span class="cite-bracket" id="mwA2Y">[</span>9<span class="cite-bracket" id="mwA2c">]</span></span></a></sup><sup about="#mwt202" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"sal"}}' id="cite_ref-sal_53-1" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-sal-53" id="mwA2g"><span class="mw-reflink-text" id="mwA2k"><span class="cite-bracket" id="mwA2o">[</span>53<span class="cite-bracket" id="mwA2s">]</span></span></a></sup></td></tr>,
 <tr id="mwA2w">
 <td id="mwA20"><a href="https://en.wikipedia.org/wiki/1582_Tenerife_plague_epidemic" id="mwA24" rel="mw:WikiLink" title="1582 Tenerife plague epidemic">1582 Tenerife plague epidemic</a> (part of the <a href="https://en.wikipedia.org/wiki/Second_plague_pandemic" id="mwA28" rel="mw:WikiLink" title="Second plague pandemic">second plague pandemic</a>)</td>
 <td id="mwA3A">1582–1583</td>
 <td id="mwA3E"><a href="https://en.wikipedia.org/wiki/Tenerife" id="mwA3I" rel="mw:WikiLink" title="Tenerife">Tenerife</a>, <a href="https://en.wikipedia.org/wiki/Spanish_Empire" id="mwA3M" rel="mw:WikiLink" title="Spanish Empire">Spain</a></td>
 <td id="mwA3Q"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwA3U" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="7000" id="mwA3Y">5,000–9,000</td>
 <td id="mwA3c"><sup about="#mwt205" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-56"}}' id="cite_ref-56" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-56" id="mwA3g"><span class="mw-reflink-text" id="mwA3k"><span class="cite-bracket" id="mwA3o">[</span>56<span class="cite-bracket" id="mwA3s">]</span></span></a></sup></td></tr>,
 <tr id="mwA3w">
 <td id="mwA30"><a class="new" data-mw-i18n='{"title":{"lang":"x-page","key":"red-link-title","params":["1592–1596 Seneca nation measles epidemic"]}}' href="https://en.wikipedia.org/wiki/1592–1596_Seneca_nation_measles_epidemic?action=edit&amp;redlink=1" id="mwA34" rel="mw:WikiLink" title="1592–1596 Seneca nation measles epidemic (page does not exist)" typeof="mw:LocalizedAttrs">1592–1596 Seneca nation measles epidemic</a></td>
 <td id="mwA38">1592–1596</td>
 <td id="mwA4A"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Seneca_nation" id="mwA4E" rel="mw:WikiLink" title="Seneca nation">Seneca nation</a>, North America</td>
 <td id="mwA4I"><a href="https://en.wikipedia.org/wiki/Measles" id="mwA4M" rel="mw:WikiLink" title="Measles">Measles</a></td>
 <td about="#mwt206" class="table-Unknown" data-mw='{"parts":["| data-sort-value=\"0\" ",{"template":{"target":{"wt":"dunno","href":"./Template:Dunno"},"params":{},"i":0}}]}' data-sort-value="0" id="mwA4Q" style="background: var(--background-color-interactive, #EEE); color: var(--color-base, black); vertical-align: middle; text-align: center; " typeof="mw:Transclusion">?</td>
 <td id="mwA4U"><sup about="#mwt209" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-57"}}' id="cite_ref-57" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-57" id="mwA4Y"><span class="mw-reflink-text" id="mwA4c"><span class="cite-bracket" id="mwA4g">[</span>57<span class="cite-bracket" id="mwA4k">]</span></span></a></sup></td></tr>,
 <tr id="mwA4o">
 <td id="mwA4s"><a href="https://en.wikipedia.org/wiki/1592–1593_Malta_plague_epidemic" id="mwA4w" rel="mw:WikiLink" title="1592–1593 Malta plague epidemic">1592–1593 Malta plague epidemic</a> (part of the <a href="https://en.wikipedia.org/wiki/Second_plague_pandemic" id="mwA40" rel="mw:WikiLink" title="Second plague pandemic">second plague pandemic</a>)</td>
 <td id="mwA44">1592–1593</td>
 <td id="mwA48"><a href="https://en.wikipedia.org/wiki/Malta" id="mwA5A" rel="mw:WikiLink" title="Malta">Malta</a></td>
 <td id="mwA5E"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwA5I" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="000003000" id="mwA5M">3,000</td>
 <td id="mwA5Q"><sup about="#mwt212" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-58"}}' id="cite_ref-58" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-58" id="mwA5U"><span class="mw-reflink-text" id="mwA5Y"><span class="cite-bracket" id="mwA5c">[</span>58<span class="cite-bracket" id="mwA5g">]</span></span></a></sup></td></tr>,
 <tr id="mwA5k">
 <td id="mwA5o"><a href="https://en.wikipedia.org/wiki/1592–1593_London_plague" id="mwA5s" rel="mw:WikiLink" title="1592–1593 London plague">1592–1593 London plague</a> (part of the <a href="https://en.wikipedia.org/wiki/Second_plague_pandemic" id="mwA5w" rel="mw:WikiLink" title="Second plague pandemic">second plague pandemic</a>)</td>
 <td id="mwA50">1592–1593</td>
 <td id="mwA54"><a href="https://en.wikipedia.org/wiki/London" id="mwA58" rel="mw:WikiLink" title="London">London</a>, England</td>
 <td id="mwA6A"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwA6E" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="000019901" id="mwA6I">19,900+</td>
 <td id="mwA6M"><sup about="#mwt215" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-59"}}' id="cite_ref-59" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-59" id="mwA6Q"><span class="mw-reflink-text" id="mwA6U"><span class="cite-bracket" id="mwA6Y">[</span>59<span class="cite-bracket" id="mwA6c">]</span></span></a></sup></td></tr>,
 <tr id="mwA6g">
 <td id="mwA6k">1596–1602 Spain plague epidemic (part of the <a href="https://en.wikipedia.org/wiki/Second_plague_pandemic" id="mwA6o" rel="mw:WikiLink" title="Second plague pandemic">second plague pandemic</a>)</td>
 <td id="mwA6s">1596–1602</td>
 <td id="mwA6w"><a href="https://en.wikipedia.org/wiki/Spanish_Empire" id="mwA60" rel="mw:WikiLink" title="Spanish Empire">Spain</a></td>
 <td id="mwA64"><a href="https://en.wikipedia.org/wiki/Bubonic_plague" id="mwA68" rel="mw:WikiLink" title="Bubonic plague">Bubonic plague</a></td>
 <td data-sort-value="650000" id="mwA7A">600,000–700,000</td>
 <td id="mwA7E"><sup about="#mwt217" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"Stanley G. Payne"},"body":{"id":"mw-reference-text-cite_note-Stanley_G._Payne-60"}}' id="cite_ref-Stanley_G._Payne_60-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-Stanley_G._Payne-60" id="mwA7I"><span class="mw-reflink-text" id="mwA7M"><span class="cite-bracket" id="mwA7Q">[</span>60<span class="cite-bracket" id="mwA7U">]</span></span></a></sup></td></tr>,
 <tr class="mw-empty-elt" id="mwA7Y"></tr>]

In [18]:
for row in column_dataB[1:-1]:
    row_dataB = row.find_all('td')
    individual_row_dataB = [dataB.text.strip() for dataB in row_dataB]
    
    
    length = len(df)
    df.loc[length] = individual_row_dataB

In [19]:
df

,Event,Years,Location,Disease,Death toll (estimate),Ref.
0,1350 BC plague of Megiddo,1350 BC (circa),"Megiddo, land of Canaan","Unknown. In the Amarna letters EA 244, Biridiy...",?,[28]
1,"Hittite Plague/""Hand of Nergal""",1330 BC (circa),"Near East, Hittite Empire, Alashiya, possibly ...","Unknown, possibly Tularemia. Mentioned in Amar...",?,
2,Plague of Athens,430–426 BC,"Greece, Libya, Egypt, Ethiopia","Unknown, possibly typhus, typhoid fever or vir...","75,000–100,000",[29][30][31][32]
3,412 BC epidemic,412 BC,"Greece (Northern Greece, Roman Republic)","Unknown, possibly influenza","473,000 (10% of the Roman Population)",[33]
4,Antonine Plague,165–180 (possibly up to 190),Roman Empire,"Unknown, possibly smallpox",5–10 million,[34][35]
5,Jian'an Plague,217,Han dynasty,"Unknown, possibly typhoid fever or viral hemor...",2 million,[12][13]
6,Plague of Cyprian,249–262,Europe,"Unknown, possibly smallpox or viral hemorrhagi...","310,000",[36][37][38]
7,Plague of Justinian (beginning of first plague...,541–549,Europe and West Asia,Bubonic plague,15–100 million,[4][39][40]
8,580 Dysentery Epidemic in Gaul,580,Gaul,Dysentery or possibly smallpox,"450,000 (10% of the Gaul population)",[41]
9,Roman Plague of 590 (part of first plague pand...,590,"Rome, Byzantine Empire",Bubonic plague,?,[42]
10,Plague of Sheroe (part of first plague pandemic),627–628,Bilad al-Sham,Bubonic plague,"25,000+",
11,Plague of Amwas (part of first plague pandemic),638–639,"Byzantine Empire, West Asia, Africa",Bubonic plague,"25,000+",[43]
12,Plague of 664 (part of first plague pandemic),664–689,British Isles,Bubonic plague,?,[44]
13,Plague of 698–701 (part of first plague pandemic),698–701,"Byzantine Empire, West Asia, Syria, Mesopotamia",Bubonic plague,?,[45]
14,735–737 Japanese smallpox epidemic,735–737,Japan,Smallpox,2 million (approx. 1⁄3 of Japanese population),[14][46]
15,Plague of 746–747 (part of first plague pandemic),746–747,"Byzantine Empire, West Asia, Africa",Bubonic plague,?,[43]
16,Black Death (start of the second plague pandemic),1346–1353,Eurasia and North Africa,Bubonic plague,25–50 million (30–60% of European population a...,[47]
17,Sweating sickness (multiple outbreaks),1485–1551,Britain (England) and later continental Europe,"Unknown, possibly an unknown species of hantav...","10,000+",[48]
18,1489 Spain typhus epidemic,1489,Spain,Typhus,"17,000",[49]
19,1510 influenza pandemic,1510,"Asia, North Africa, Europe",Influenza,"Unknown, around 1% of those infected",[50]
20,1520 Mexico smallpox epidemic,1519–1520,Mexico,Smallpox,5–8 million (40% of population),[9]
21,Cocoliztli epidemic of 1545–1548,1545–1548,Mexico,Possibly Salmonella enterica,5–15 million (80% of population),[51][52][9][53]
22,1557 influenza pandemic,1557–1559,"Asia, Africa, Europe, and Americas",Influenza,Unknown (10% of the infected),
23,1561 Chile smallpox epidemic,1561–1562,Chile,Smallpox,"120,000–150,000 (20–25% of native population)",[54]
24,1563 London plague (part of the second plague ...,1563–1564,"London, England",Bubonic plague,"20,100+",[55]
25,Cocoliztli epidemic of 1576,1576–1580,Mexico,Possibly Salmonella enterica,2–2.5 million (50% of population),[51][52][9][53]
26,1582 Tenerife plague epidemic (part of the sec...,1582–1583,"Tenerife, Spain",Bubonic plague,"5,000–9,000",[56]
27,1592–1596 Seneca nation measles epidemic,1592–1596,"Seneca nation, North America",Measles,?,[57]
28,1592–1593 Malta plague epidemic (part of the s...,1592–1593,Malta,Bubonic plague,"3,000",[58]
29,1592–1593 London plague (part of the second pl...,1592–1593,"London, England",Bubonic plague,"19,900+",[59]
30,1596–1602 Spain plague epidemic (part of the s...,1596–1602,Spain,Bubonic plague,"600,000–700,000",[60]

In [20]:
# now for table 3

table3 = target_tables[2]
column_dataC = table3.find_all('tr')

for row in column_dataC[1:-1]:
    row_dataC = row.find_all('td')
    individual_row_dataC = [dataC.text.strip() for dataC in row_dataC]
    
    length= len(df)
    df.loc[length] = individual_row_dataC

In [21]:
df

,Event,Years,Location,Disease,Death toll (estimate),Ref.
0,1350 BC plague of Megiddo,1350 BC (circa),"Megiddo, land of Canaan","Unknown. In the Amarna letters EA 244, Biridiy...",?,[28]
1,"Hittite Plague/""Hand of Nergal""",1330 BC (circa),"Near East, Hittite Empire, Alashiya, possibly ...","Unknown, possibly Tularemia. Mentioned in Amar...",?,
2,Plague of Athens,430–426 BC,"Greece, Libya, Egypt, Ethiopia","Unknown, possibly typhus, typhoid fever or vir...","75,000–100,000",[29][30][31][32]
3,412 BC epidemic,412 BC,"Greece (Northern Greece, Roman Republic)","Unknown, possibly influenza","473,000 (10% of the Roman Population)",[33]
4,Antonine Plague,165–180 (possibly up to 190),Roman Empire,"Unknown, possibly smallpox",5–10 million,[34][35]
5,Jian'an Plague,217,Han dynasty,"Unknown, possibly typhoid fever or viral hemor...",2 million,[12][13]
6,Plague of Cyprian,249–262,Europe,"Unknown, possibly smallpox or viral hemorrhagi...","310,000",[36][37][38]
7,Plague of Justinian (beginning of first plague...,541–549,Europe and West Asia,Bubonic plague,15–100 million,[4][39][40]
8,580 Dysentery Epidemic in Gaul,580,Gaul,Dysentery or possibly smallpox,"450,000 (10% of the Gaul population)",[41]
9,Roman Plague of 590 (part of first plague pand...,590,"Rome, Byzantine Empire",Bubonic plague,?,[42]
10,Plague of Sheroe (part of first plague pandemic),627–628,Bilad al-Sham,Bubonic plague,"25,000+",
11,Plague of Amwas (part of first plague pandemic),638–639,"Byzantine Empire, West Asia, Africa",Bubonic plague,"25,000+",[43]
12,Plague of 664 (part of first plague pandemic),664–689,British Isles,Bubonic plague,?,[44]
13,Plague of 698–701 (part of first plague pandemic),698–701,"Byzantine Empire, West Asia, Syria, Mesopotamia",Bubonic plague,?,[45]
14,735–737 Japanese smallpox epidemic,735–737,Japan,Smallpox,2 million (approx. 1⁄3 of Japanese population),[14][46]
15,Plague of 746–747 (part of first plague pandemic),746–747,"Byzantine Empire, West Asia, Africa",Bubonic plague,?,[43]
16,Black Death (start of the second plague pandemic),1346–1353,Eurasia and North Africa,Bubonic plague,25–50 million (30–60% of European population a...,[47]
17,Sweating sickness (multiple outbreaks),1485–1551,Britain (England) and later continental Europe,"Unknown, possibly an unknown species of hantav...","10,000+",[48]
18,1489 Spain typhus epidemic,1489,Spain,Typhus,"17,000",[49]
19,1510 influenza pandemic,1510,"Asia, North Africa, Europe",Influenza,"Unknown, around 1% of those infected",[50]
20,1520 Mexico smallpox epidemic,1519–1520,Mexico,Smallpox,5–8 million (40% of population),[9]
21,Cocoliztli epidemic of 1545–1548,1545–1548,Mexico,Possibly Salmonella enterica,5–15 million (80% of population),[51][52][9][53]
22,1557 influenza pandemic,1557–1559,"Asia, Africa, Europe, and Americas",Influenza,Unknown (10% of the infected),
23,1561 Chile smallpox epidemic,1561–1562,Chile,Smallpox,"120,000–150,000 (20–25% of native population)",[54]
24,1563 London plague (part of the second plague ...,1563–1564,"London, England",Bubonic plague,"20,100+",[55]
25,Cocoliztli epidemic of 1576,1576–1580,Mexico,Possibly Salmonella enterica,2–2.5 million (50% of population),[51][52][9][53]
26,1582 Tenerife plague epidemic (part of the sec...,1582–1583,"Tenerife, Spain",Bubonic plague,"5,000–9,000",[56]
27,1592–1596 Seneca nation measles epidemic,1592–1596,"Seneca nation, North America",Measles,?,[57]
28,1592–1593 Malta plague epidemic (part of the s...,1592–1593,Malta,Bubonic plague,"3,000",[58]
29,1592–1593 London plague (part of the second pl...,1592–1593,"London, England",Bubonic plague,"19,900+",[59]
30,1596–1602 Spain plague epidemic (part of the s...,1596–1602,Spain,Bubonic plague,"600,000–700,000",[60]
31,1603 London plague (part of the second plague ...,1603,"London, England",Bubonic plague,"40,000",[61][62][63]
32,1616 New England infections epidemic,1616–1620,"Southern New England, British North America, e...","Unknown, possibly leptospirosis with Weil synd...","1,143–3,429 (estimated 30–90% of population)",[64][65]
33,1629–1631 Italian plague (part of the second p...,1629–1631,Italy,Bubonic plague,1 million,[66]
34,1632–1635 Augsburg plague epidemic (part of th...,1632–1635,"Augsburg, Germany",Bubonic plague,"13,712",[67]
35,Massachusetts smallpox epidemic,1633–1634,"Massachusetts Bay Colony, Thirteen Colonies",Smallpox,"1,000",[68]
36,1634–1640 Wyandot people epidemic,1634–1640,"Wyandot people, North America",Smallpox and Influenza,"15,000–25,000",[69]
37,1637 London plague epidemic (part of the secon...,1636–1637,"London and Westminster, England",Bubonic plague,"10,400",[70]
38,Great Plague in the late Ming dynasty (part of...,1633–1644,China,Bubonic plague,"200,000+",[71][72]
39,Great Plague of Seville (part of the second pl...,1647–1652,Spain,Bubonic plague,"500,000",[60]
40,1648 Central America yellow fever epidemic,1648,Central America,Yellow fever,?,[73]
41,Naples Plague (part of the second plague pande...,1656–1658,Italy,Bubonic plague,"1,250,000",[74]
42,1663–1664 Amsterdam plague epidemic (part of t...,1663–1664,"Amsterdam, Netherlands",Bubonic plague,"24,148",[75]
43,Great Plague of London (part of the second pla...,1665–1666,England,Bubonic plague,"100,000",[76][77]
44,1668 France plague (part of the second plague ...,1668,France,Bubonic plague,"40,000",[78]
45,1675–1676 Malta plague epidemic (part of the s...,1675–1676,Malta,Bubonic plague,"11,300",[79]
46,1676–1685 Spain plague (part of the second pla...,1676–1685,Spain,Bubonic plague,?,[80]
47,1677–1678 Boston smallpox epidemic,1677–1678,"Massachusetts Bay Colony, British North America",Smallpox,"750–1,000",[81]
48,Great Plague of Vienna (part of the second pla...,1679,"Vienna, Austria",Bubonic plague,"76,000",[82]
49,1681 Prague plague epidemic (part of the secon...,1681,"Prague, Czech Kingdom",Bubonic plague,"83,000",[83]
50,1687 South Africa influenza outbreak,1687,South Africa,"Unknown, possibly influenza",?,[84]
51,1693 Boston yellow fever epidemic,1693,"Boston, Massachusetts Bay Colony, British Nort...",Yellow fever,"3,100+",[85]
52,1699 Charleston and Philadelphia yellow fever ...,1699,"Charleston and Philadelphia, British North Ame...",Yellow fever,"520 (300 in Charleston, 220 in Philadelphia)",[86]

In [22]:
# now for table 4
table4 = target_tables[3]

column_dataD = table4.find_all('tr')

for row in column_dataD[1:-1]:
    row_dataD = row.find_all('td')
    individual_row_dataD = [dataD.text.strip() for dataD in row_dataD]
    
    length= len(df)
    df.loc[length] = individual_row_dataD

In [23]:
df

,Event,Years,Location,Disease,Death toll (estimate),Ref.
0,1350 BC plague of Megiddo,1350 BC (circa),"Megiddo, land of Canaan","Unknown. In the Amarna letters EA 244, Biridiy...",?,[28]
1,"Hittite Plague/""Hand of Nergal""",1330 BC (circa),"Near East, Hittite Empire, Alashiya, possibly ...","Unknown, possibly Tularemia. Mentioned in Amar...",?,
2,Plague of Athens,430–426 BC,"Greece, Libya, Egypt, Ethiopia","Unknown, possibly typhus, typhoid fever or vir...","75,000–100,000",[29][30][31][32]
3,412 BC epidemic,412 BC,"Greece (Northern Greece, Roman Republic)","Unknown, possibly influenza","473,000 (10% of the Roman Population)",[33]
4,Antonine Plague,165–180 (possibly up to 190),Roman Empire,"Unknown, possibly smallpox",5–10 million,[34][35]
...,...,...,...,...,...,...
77,1778 Spain dengue fever outbreak,1778,Spain,Dengue fever,?,[115]
78,1782 Influenza pandemic,1782,Worldwide,Influenza,?,
79,1788 Pueblo Indians smallpox epidemic,1788,Pueblo Indians in northern New Spain (what is ...,Smallpox,?,[116]
80,1789–1790 New South Wales smallpox epidemic,1789–1790,"New South Wales, Australia",Smallpox,"125,251–175,351 (50–70% of native population)",[117][118]
81,1793 Philadelphia yellow fever epidemic,1793,"Philadelphia, United States",Yellow fever,"5,000+",[119]

In [24]:
# now for table 5
table5 = target_tables[4]

column_dataE = table5.find_all('tr')

for row in column_dataE[1:-1]:
    row_dataE = row.find_all('td')
    individual_row_dataE = [dataE.text.strip() for dataE in row_dataE]
    
    length= len(df)
    df.loc[length] = individual_row_dataE

In [25]:
# now for table 6
table6 = target_tables[5]

column_dataF = table6.find_all('tr')

for row in column_dataF[1:-1]:
    row_dataF = row.find_all('td')
    individual_row_dataF = [dataF.text.strip() for dataF in row_dataF]
    
    length= len(df)
    df.loc[length] = individual_row_dataF

In [26]:
df.tail(10)

,Event,Years,Location,Disease,Death toll (estimate),Ref.
171,1986 Oju yellow fever epidemic,1986,"Oju, Nigeria",Yellow fever,"5,600+",[214]
172,1987 Mali yellow fever epidemic,1987,Mali,Yellow fever,145,[215]
173,1988 Shanghai hepatitis A epidemic,1988,"Shanghai, China",Hepatitis A,31–47,[216][217][218]
174,1991 Bangladesh cholera epidemic,1991,Bangladesh,Cholera,"8,410–9,432",[219]
175,1991 Latin America cholera epidemic,1991–1993,"Peru, Chile, Bolivia, Ecuador, Colombia, Mexic...",Cholera,"8,000",[220][221]
176,1994 plague in India,1994,India,Bubonic plague and Pneumonic plague,56,[222]
177,United Kingdom BSE outbreak,1996–2001,United Kingdom,Variant Creutzfeldt–Jakob disease / vCJD,178,[223][224]
178,1996 West Africa meningitis epidemic,1996,West Africa,Meningitis,"10,000",[225]
179,1998–1999 Malaysia Nipah virus outbreak,1998–1999,Malaysia,Nipah virus infection,105,[226]
180,1998–2000 Democratic Republic of the Congo Mar...,1998–2000,Democratic Republic of the Congo,Marburg virus,128,[227]

In [27]:
# now for table 7
table7 = target_tables[6]
column_dataG = table7.find_all('tr')

for row in column_dataG[1:-1]:
    row_dataG = row.find_all('td', recursive=False)
    individual_row_dataG = [dataG.text.strip() for dataG in row_dataG]

    if len(individual_row_dataG) == len(df.columns):
        df.loc[len(df)] = individual_row_dataG
    else:
        print("Column mismatch:")
        print(individual_row_dataG)

Column mismatch:
['284,000 (possible range 151,700–575,400)', '[263]']
Column mismatch:
[]
Column mismatch:
[]

In [28]:
df

,Event,Years,Location,Disease,Death toll (estimate),Ref.
0,1350 BC plague of Megiddo,1350 BC (circa),"Megiddo, land of Canaan","Unknown. In the Amarna letters EA 244, Biridiy...",?,[28]
1,"Hittite Plague/""Hand of Nergal""",1330 BC (circa),"Near East, Hittite Empire, Alashiya, possibly ...","Unknown, possibly Tularemia. Mentioned in Amar...",?,
2,Plague of Athens,430–426 BC,"Greece, Libya, Egypt, Ethiopia","Unknown, possibly typhus, typhoid fever or vir...","75,000–100,000",[29][30][31][32]
3,412 BC epidemic,412 BC,"Greece (Northern Greece, Roman Republic)","Unknown, possibly influenza","473,000 (10% of the Roman Population)",[33]
4,Antonine Plague,165–180 (possibly up to 190),Roman Empire,"Unknown, possibly smallpox",5–10 million,[34][35]
...,...,...,...,...,...,...
257,2023–2024 Bangsamoro measles outbreak,2023–2024,"Bangsamoro, Philippines",Measles,14,
258,2023–2024 Oropouche virus disease outbreak,2023–2024,Brazil,Oropouche fever,2,[318][319][320]
259,2024 American dengue epidemic,2024,Latin America and the Caribbean,Dengue fever,"9,875",[321]
260,2024 Kwango province malaria outbreak,2024,Democratic Republic of the Congo,Malaria,143,[322]
261,MV Hondius hantavirus outbreak,2026,MV Hondius,Hantavirus pulmonary syndrome,3,[323]

In [29]:
# now for table 8
table8 = target_tables[7]

column_dataH = table8.find_all('tr')

for row in column_dataH[1:-1]:
    row_dataH = row.find_all('td')
    individual_row_dataH = [dataH.text.strip() for dataH in row_dataH]
    
    length= len(df)
    df.loc[length] = individual_row_dataH

In [30]:
df

,Event,Years,Location,Disease,Death toll (estimate),Ref.
0,1350 BC plague of Megiddo,1350 BC (circa),"Megiddo, land of Canaan","Unknown. In the Amarna letters EA 244, Biridiy...",?,[28]
1,"Hittite Plague/""Hand of Nergal""",1330 BC (circa),"Near East, Hittite Empire, Alashiya, possibly ...","Unknown, possibly Tularemia. Mentioned in Amar...",?,
2,Plague of Athens,430–426 BC,"Greece, Libya, Egypt, Ethiopia","Unknown, possibly typhus, typhoid fever or vir...","75,000–100,000",[29][30][31][32]
3,412 BC epidemic,412 BC,"Greece (Northern Greece, Roman Republic)","Unknown, possibly influenza","473,000 (10% of the Roman Population)",[33]
4,Antonine Plague,165–180 (possibly up to 190),Roman Empire,"Unknown, possibly smallpox",5–10 million,[34][35]
...,...,...,...,...,...,...
266,2023–2026 mpox epidemic,2023–present,"Worldwide, primarily Africa",Mpox,812,[330]
267,2024–2026 Sudanese cholera epidemic,2024–present,"Sudan, South Sudan, and Chad",Cholera,3573,[331]
268,2026 Bangladesh measles outbreak,2026–present,Bangladesh,Measles,"1,009",[332]
269,2026 Ebola epidemic,2026–present,"Democratic Republic of the Congo, Uganda",Ebola,"4,151",[333]
270,2026 United States cyclosporiasis outbreak,2026,United States,Cyclosporiasis,2,[334]

In [31]:
from sqlalchemy import create_engine

In [32]:
connection_string = (
    "mssql+pyodbc://localhost/EpidemicsDB"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

engine = create_engine(connection_string)

In [33]:
! pip install pypyodbc
import pypyodbc as odbc

Requirement already satisfied: pypyodbc in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.3.6)
Requirement already satisfied: setuptools in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pypyodbc) (84.0.0)

In [34]:
import urllib
from sqlalchemy import create_engine

# 1. DATABASE CONFIGURATION

SERVER = r"AwesomeDad\SQLEXPRESS"
DATABASE = "EpidemicDB"
TARGET_TABLE = "EpidemicData"  # table name

connection_string = f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={SERVER};DATABASE={DATABASE};Trusted_Connection=yes;"

# 2. CREATE THE SQLALCHEMY ENGINE

params = urllib.parse.quote_plus(connection_string)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")


# 3. UPLOAD DATAFRAME TO SQL SERVER
 
try:
    print("Connecting to SQL Server and uploading data...")
    df.to_sql(name=TARGET_TABLE, con=engine, index=False, if_exists='replace')
    print(f"Success! Data successfully written to the '{TARGET_TABLE}' table in '{DATABASE}'.")

except Exception as e:
    print("\n[ERROR] The upload failed. Detailed error message below:")
    print(e)

Connecting to SQL Server and uploading data...
Success! Data successfully written to the 'EpidemicData' table in 'EpidemicDB'.

In [35]:
df.to_csv('epidemic_data.csv', index= False)
print("Success! DataFrame saved locally as 'epidemic_data.csv'.")

Success! DataFrame saved locally as 'epidemic_data.csv'.

In [36]:
# for the references
references= webpage.find("div", id= 'mwEjU')
ref_headers = ['ref_num', 'Reference']

rows = []

if references:
    all_references = references.find_all("li")  

    # 3. Loop through EVERY reference list item and add them to rows
    for index, item in enumerate(all_references, start=1):
        ref_text = item.text.strip()  # Get the clean text
        
        if ref_text:  # Skip if the item is blank
            rows.append({"ref_num": index, "Reference": ref_text})

#  to the DataFrame
ref_df = pd.DataFrame(rows, columns=ref_headers)

# 5.Progress report
print(f"Extracted {len(ref_df)} references.")

Extracted 334 references.

In [37]:
# upload the references to the database
try:
    print("Connecting to SQL Server and uploading data...")
    ref_df.to_sql(name= 'ReferenceData', con=engine, index=False, if_exists='replace')
    print(f"Success! Data successfully written to the 'ReferenceData' table in '{DATABASE}'.")

except Exception as e:
    print("\n[ERROR] The upload failed. Detailed error message below:")
    print(e)

Connecting to SQL Server and uploading data...
Success! Data successfully written to the 'ReferenceData' table in 'EpidemicDB'.